name: Create Yuescript Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change directory
        run: cd $GITHUB_WORKSPACE

      # - name: Update apt
      #   run: sudo apt-get update -y

      # - name: Install LuaRocks
      #   run: sudo apt-get install -y luarocks

      # - name: Install Yuescript
      #   run: sudo luarocks install yuescript

      - name: Build Lua
        run: ./.github/yue ./

      - name: Remove yue
        run: find . -type f -name '*.yue' -delete

      - name: Remove github dir
        run: rm -rf .github

      - name: Remove .gitignore
        run: rm -f .gitignore

      - name: Remove .gitattributes
        run: rm -f .gitattributes

      - name: Remove todo.md
        run: rm -f todo.md

      - name: Create VERSION file
        run: versionStr=${{ github.ref }};echo -e v${versionStr#*v} > VERSION

      - name: Push to lua branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release build: $(cat VERSION)"
          git push -f origin HEAD:lua

      - name: Remove .git dir
        run: rm -rf .git

      - name: Create subdirectory
        run: mkdir ${{ github.event.repository.name }}

      - name: Move files into sub directory
        run: ls | grep -v ${{ github.event.repository.name }} | xargs mv -t ${{ github.event.repository.name }}

      - name: Create Release Asset
        run: zip -r9 ${{ github.event.repository.name }}.zip .

      - name: Publish Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./${{ github.event.repository.name }}.zip
