name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change directory
        run: cd $GITHUB_WORKSPACE

      - name: Remove unused files and folders
        run: |
          rm -rf .github
          rm -rf .git

      - name: Create VERSION file
        run: echo -e ${{ github.ref_name }} > VERSION

      - name: Create subdirectory
        run: mkdir ${{ github.event.repository.name }}

      - name: Move files into sub directory
        run: ls | grep -v ${{ github.event.repository.name }} | xargs mv -t ${{ github.event.repository.name }}

      - name: Create Release Asset
        run: zip -r9 ${{ github.event.repository.name }}.zip .

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./${{ github.event.repository.name }}.zip
